In [ ]:
import pandas as pd

print("Pandas Version:", pd.__version__)

Pandas Version: 2.2.2

In [ ]:
student = pd.Series(["Ram","John","Priya","Kiran"])

print(student)

0      Ram
1     John
2    Priya
3    Kiran
dtype: object

In [ ]:
data = {
    "ID":[101,102,103,104],
    "Name":["Ram","John","Priya","Kiran"],
    "Age":[20,21,20,22],
    "Department":["IT","CSE","ECE","AIDS"],
    "Marks":[85,90,88,95]
}

df = pd.DataFrame(data)

df

    ID   Name  Age Department  Marks
0  101    Ram   20         IT     85
1  102   John   21        CSE     90
2  103  Priya   20        ECE     88
3  104  Kiran   22       AIDS     95

In [ ]:
print(df.head())

print(df.tail())

    ID   Name  Age Department  Marks
0  101    Ram   20         IT     85
1  102   John   21        CSE     90
2  103  Priya   20        ECE     88
3  104  Kiran   22       AIDS     95
    ID   Name  Age Department  Marks
0  101    Ram   20         IT     85
1  102   John   21        CSE     90
2  103  Priya   20        ECE     88
3  104  Kiran   22       AIDS     95

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          4 non-null      int64
 1   Name        4 non-null      object
 2   Age         4 non-null      int64
 3   Department  4 non-null      object
 4   Marks       4 non-null      int64
dtypes: int64(3), object(2)
memory usage: 292.0+ bytes

In [ ]:
df.describe()

               ID        Age      Marks
count    4.000000   4.000000   4.000000
mean   102.500000  20.750000  89.500000
std      1.290994   0.957427   4.203173
min    101.000000  20.000000  85.000000
25%    101.750000  20.000000  87.250000
50%    102.500000  20.500000  89.000000
75%    103.250000  21.250000  91.250000
max    104.000000  22.000000  95.000000

In [ ]:
print(df.shape)

(4, 5)

In [ ]:
print(df.columns)

Index(['ID', 'Name', 'Age', 'Department', 'Marks'], dtype='object')

In [ ]:
print(df.dtypes)

ID             int64
Name          object
Age            int64
Department    object
Marks          int64
dtype: object

In [ ]:
df["Name"]

0      Ram
1     John
2    Priya
3    Kiran
Name: Name, dtype: object

In [ ]:
df[["Name","Marks"]]

    Name  Marks
0    Ram     85
1   John     90
2  Priya     88
3  Kiran     95

In [ ]:
df.iloc[0]

ID            101
Name          Ram
Age            20
Department     IT
Marks          85
Name: 0, dtype: object

In [ ]:
df.iloc[1:3]

    ID   Name  Age Department  Marks
1  102   John   21        CSE     90
2  103  Priya   20        ECE     88

In [ ]:
df.loc[2]

ID              103
Name          Priya
Age              20
Department      ECE
Marks            88
Name: 2, dtype: object

In [ ]:
df[df["Marks"]>85]

    ID   Name  Age Department  Marks
1  102   John   21        CSE     90
2  103  Priya   20        ECE     88
3  104  Kiran   22       AIDS     95

In [ ]:
df.sort_values(by="Marks")

    ID   Name  Age Department  Marks
0  101    Ram   20         IT     85
2  103  Priya   20        ECE     88
1  102   John   21        CSE     90
3  104  Kiran   22       AIDS     95

In [ ]:
df.sort_values(by="Marks")

    ID   Name  Age Department  Marks
0  101    Ram   20         IT     85
2  103  Priya   20        ECE     88
1  102   John   21        CSE     90
3  104  Kiran   22       AIDS     95

In [ ]:
df.sort_values(by="Marks",ascending=False)

    ID   Name  Age Department  Marks
3  104  Kiran   22       AIDS     95
1  102   John   21        CSE     90
2  103  Priya   20        ECE     88
0  101    Ram   20         IT     85

In [ ]:
df["Result"]="Pass"

df

    ID   Name  Age Department  Marks Result
0  101    Ram   20         IT     85   Pass
1  102   John   21        CSE     90   Pass
2  103  Priya   20        ECE     88   Pass
3  104  Kiran   22       AIDS     95   Pass

In [ ]:
df["Marks"]=df["Marks"]+5

df

    ID   Name  Age Department  Marks Result
0  101    Ram   20         IT     90   Pass
1  102   John   21        CSE     95   Pass
2  103  Priya   20        ECE     93   Pass
3  104  Kiran   22       AIDS    100   Pass

In [ ]:
df.rename(columns={"Marks":"Score"})

    ID   Name  Age Department  Score Result
0  101    Ram   20         IT     90   Pass
1  102   John   21        CSE     95   Pass
2  103  Priya   20        ECE     93   Pass
3  104  Kiran   22       AIDS    100   Pass

In [ ]:
df.drop(columns=["Age"])

    ID   Name Department  Marks Result
0  101    Ram         IT     90   Pass
1  102   John        CSE     95   Pass
2  103  Priya        ECE     93   Pass
3  104  Kiran       AIDS    100   Pass

In [ ]:
data={
    "Name":["Ram","John","Sara"],
    "Marks":[90,None,85]
}

df=pd.DataFrame(data)

df

   Name  Marks
0   Ram   90.0
1  John    NaN
2  Sara   85.0

In [ ]:
df.isnull()

    Name  Marks
0  False  False
1  False   True
2  False  False

In [ ]:
df.isnull().sum()

Name     0
Marks    1
dtype: int64

In [ ]:
df.fillna(0)

   Name  Marks
0   Ram   90.0
1  John    0.0
2  Sara   85.0

In [ ]:
df.dropna()

   Name  Marks
0   Ram   90.0
2  Sara   85.0

In [ ]:
data={
    "Department":["IT","IT","CSE","CSE"],
    "Marks":[80,90,85,95]
}

df=pd.DataFrame(data)

df.groupby("Department").mean()

            Marks
Department
CSE          90.0
IT           85.0

In [ ]:
df["Department"].value_counts()

Department
IT     2
CSE    2
Name: count, dtype: int64

In [ ]:
student=pd.DataFrame({
    "ID":[1,2,3],
    "Name":["Ram","John","Sara"]
})

marks=pd.DataFrame({
    "ID":[1,2,3],
    "Marks":[90,80,85]
})

pd.merge(student,marks,on="ID")

   ID  Name  Marks
0   1   Ram     90
1   2  John     80
2   3  Sara     85

In [ ]:
df1=pd.DataFrame({"A":[1,2]})

df2=pd.DataFrame({"A":[3,4]})

pd.concat([df1,df2])

   A
0  1
1  2
0  3
1  4

In [ ]:
data={
    "Name":["Ram","Ram","Sara"],
    "Marks":[90,90,80]
}

df=pd.DataFrame(data)

df.drop_duplicates()

   Name  Marks
0   Ram     90
2  Sara     80

In [ ]:
data={
    "Name":["ram","john","sara"]
}

df=pd.DataFrame(data)

df["Name"].str.upper()

0     RAM
1    JOHN
2    SARA
Name: Name, dtype: object

In [ ]:
dates=pd.date_range("2025-01-01",periods=5)

print(dates)

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
student={
    "Name":["Ram","John","Sara","Kiran"],
    "Marks":[90,80,95,88]
}

df=pd.DataFrame(student)

print("Average Marks:",df["Marks"].mean())

print("Highest Marks:",df["Marks"].max())

print(df[df["Marks"]>85])

Average Marks: 88.25
Highest Marks: 95
    Name  Marks
0    Ram     90
2   Sara     95
3  Kiran     88